#!/bin/sh

BASE_DIR="$(cd "$(dirname "$0")" && pwd -P)" # Get current pwd

bspc config border_width 2
bspc config window_gap 10
bspc config single_monocle false
bspc config split_ratio 0.52
bspc config borderless_monocle false
bspc config gapless_monocle false

focused_border=$(xrdb -query | grep 'pink' | awk '{print $2}')
bspc config focused_border_color "$focused_border"

# Rules
bspc rule -a kitty state=floating center=true rectangle=870x450+0+0

# Set wallpaper
WALLPAPER="$BASE_DIR/wallpaper.sh"
[ -f "$WALLPAPER" ] && chmod +x "$WALLPAPER"; "$WALLPAPER"

sxhkd &
# setxkbmap fr &
# picom --config $XDG_CONFIG_HOME/picom/picom.conf &
# $XDG_CONFIG_HOME/eww/eww.sh init &
# eww open bar &
